### ISSUE TITLE
Add link to docs

### ISSUE THREAD

**Issue by corysimmons** [davidkpiano/sassdash#11]
At top of repo page add link to http://davidkpiano.github.io/sassdash

**Comment by davidkpiano** [comment]
Thanks: Added here: cfb968f214cab5c06c5757a90acebf1a4f1606ce

**Comment by corysimmons** [comment]
hehe thanks but I meant here:

![](http://i.imgur.com/rKcjGAN.png)

**Comment by davidkpiano** [comment]
Oops. Should be added now.

**Comment by corysimmons** [comment]
:+1: XD
