### ISSUE TITLE
Build to a single file library

### ISSUE THREAD

**Issue by kaelig** [davidkpiano/sassdash#12]
Importing a lot of files can be costly for the Sass build process and impact performance badly.

How about shipping a built version of all files concatenated into one (on medium to large codebases I expect that this would have a massive impact on build times)?

**Comment by davidkpiano** [comment]
@kaelig Great suggestion - it's been something I've been meaning to look into. I want to eventually accomplish two things:
- [ ] Include a built (dist.) single-file version (need to include a build step - short-term goal)
- [ ] Implement a modular import file structure that lets developers only include the functions they need, e.g. `@import 'sassdash/modules/intersection';` (longer term goal)

**Comment by kaelig** [comment]
Hopefully you'll be able to do the latter with Sass 4.0 :pray:

**Comment by lunelson** [comment]
You could use [sass-graph](https://github.com/xzyfer/sass-graph) to parse out the dependency tree and feed this to a `concat` step, e.g. with gulp

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
