### ISSUE TITLE
__get and _omit does not acknowledge maps with lists as keys

### ISSUE THREAD

**Issue by mil** [davidkpiano/sassdash#20]
Currently using `_omit` with a map that has a list as a key will make `_omit` return the map with the value of all list's keys as `null` (affects `_pick` too).  I wrote the following test which fails currently to demonstrate the problem:
https://github.com/mil/sassdash/commit/cb6e867c834e5e948e98606860e3ce7f02b9a5d4

Tracing this down, the problem is with the `__get` internal function which doesn't acknowledge maps with lists as keys. The `__get` function is a little bit too involved for me to debug, but please let me know if this is by design or something that could be fixed.

**Comment by davidkpiano** [comment]
Thanks for the report, @mil! I was able to replicate this issue and will have a fix for it soon.

**Comment by davidkpiano** [comment]
Fixed here: https://github.com/davidkpiano/sassdash/commit/2c8500f143bb082702008fe96a2f8a7c3aecdb33

Version pushed to `sassdash@0.7.2`

**Comment by mil** [comment]
Thanks for your speedy patching
