### ISSUE TITLE
Unexpected trim results

### ISSUE THREAD

**Issue by ellioseven** [davidkpiano/sassdash#28]
Getting an issue where sassdash will be too greedy when trimming characters like so:

```
$key: _trim("a--b--c--", "--");
@debug "Result: " + $key;
```

Results in:

```
DEBUG: Result: s
```

Which should be:

```
DEBUG: Result: a--b--c
```

**Comment by P233** [comment]
@davidkpiano The `__chars-index` function can not help when there is more than one character. In this case, I think it's better to split the `$chars` to a list, and iteratively slice the candidate character from the list on both sides of the string.

**Comment by davidkpiano** [comment]
Would be happy to accept a PR for this.
