### ISSUE TITLE
Sass 3.5 compatibility: Use call(get-function('foo'), $args) instead of call('foo', $args)

### ISSUE THREAD

**Issue by kaelig** [davidkpiano/sassdash#29]
`call('function', $args)` is deprecated in Sass 3.5 and won't work in Sass 4.0 (see [release notes](http://blog.sass-lang.com/posts/809572-sass-35-release-candidate)).

This is how get-function works (unfortunately Sassmeister can't show this to you at the moment), hopefully this helps: https://github.com/kaelig/sass-first-class-functions

**Comment by josefglatz** [comment]
can this issue be closed, as such a similar case is already fixed #37
