### ISSUE TITLE
Update contribution guidelines

### ISSUE THREAD

**Issue by mmintel** [davidkpiano/sassdash#30]
Hi there,

I was going to insert some functions to my fork but the tests won't work.

1. README says I should install true via bower, is this still needed?
2. `npm run test` throws:

```
/sassdash/node_modules/sass-true/node_modules/node-sass/lib/index.js:440
  throw assign(new Error(), JSON.parse(result.error));

Error: File to import not found or unreadable: property-of
Parent style sheet: /sassdash/tests/api/_module.scss
```

What's wrong? :/

Cheers!

**Comment by davidkpiano** [comment]
I'll investigate this, thanks!

**Comment by mmintel** [comment]
as you seem to be busy atm I found it myself! :) I created a PR for this, let me know if this helps you :)

https://github.com/davidkpiano/sassdash/pull/31
