### ISSUE TITLE
Error: Invalid US-ASCII character

### ISSUE THREAD

**Issue by lianee** [davidkpiano/sassdash#34]
Compiling CLI with sass 3.4.23, ruby 2.1.5p273, I get this error:
Error: Invalid US-ASCII character

it is caused by a few UTF-8 chars in 2 files, /constants/_native.scss and api/_compare.scss.

removing the offending chars, or putting the following on first line of both files does work
`@charset "UTF-8";`

**Comment by davidkpiano** [comment]
Would you mind doing that and creating a PR? 😄 🙏
