### ISSUE TITLE
"DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal in Sass 4.0" with lib-sass 3.5.0

### ISSUE THREAD

**Issue by jrencz** [davidkpiano/sassdash#37]
Since  [sass/node-sass](https://github.com/sass/node-sass/) now uses lib-sass 3.5.0 (since https://github.com/sass/node-sass/commit/fe572eb1868ec7db2ea1a2d51fbae5aab5fe6419, release [4.8.0](https://github.com/sass/node-sass/releases/tag/v4.8.0)) and [lib-sass warns if a string is passed to `call()`](https://github.com/sass/libsass/blame/3.5-stable/src/functions.cpp#L1854) sassdash started yielding A LOT of deprecation warnings like this one:

```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("--kebab-case-compounder")) instead.
```

It will probably take a while until sass 4.0 is released, but I predict a lot of people will look for the source of those errors.

There's already a bunch of reports about this kind of warning:

https://github.com/mmistakes/minimal-mistakes/issues/1114
https://github.com/mtlynch/mtlynch.io/issues/76
https://github.com/mmistakes/jekyll-theme-basically-basic/issues/21

(those are from rubyland, where this warning surfaced earlier)

**Comment by lehni** [comment]
I think this is the same issue as #29. I'd love to see this addressed, as node-sass 4.8.3 is flooding my terminal with endless warnings now...

@davidkpiano is there a plan to address this issue?

**Comment by davidkpiano** [comment]
@lehni I don't have time at the moment but feel free to create a PR, and I will review it, merge it, and release it promptly.

**Comment by lehni** [comment]
@davidkpiano I've looked into it, but it's over my head ATM. I didn't even manage to get the tests to run, with the standard dependencies... I am getting this error:

```
Error: Invalid CSS after "...d: (('b', 'c'):": expected ")", was "'test2');"
```

**Comment by Nr9** [comment]
I completed the pull request

**Comment by davidkpiano** [comment]
Fixed in #38

**Comment by davidkpiano** [comment]
And released in 0.9.0 🎉

**Comment by lehni** [comment]
Wow, amazing! Thank you @Nr9 and @davidkpiano for releasing so quickly!

Looking at the fix, I am wondering if a `call_function($str)` helper that calls `call(get_function($str))` would be of use?

**Comment by lehni** [comment]
@davidkpiano would you mind releasing a new version of https://github.com/davidkpiano/sass-svg also that uses 0.9.0?
