### ISSUE TITLE
Push code for 0.9.0

### ISSUE THREAD

**Issue by kturney** [davidkpiano/sassdash#40]
looks like the code for 0.9.0 (latest on npm at time of issue creation) has not been pushed up yet.

Thanks!

**Comment by jonscottclark** [comment]
This would be great to see, as well as marking 0.9.0 as the latest release in GitHub :)

**Comment by davidkpiano** [comment]
Done!

**Comment by jonscottclark** [comment]
Thanks @davidkpiano, just need tags updated here as well. p.s. Trying out sassdash for the first time today, really nice work! :)
